# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'snackspopnew' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
   	use_frameworks!
	pod "ECDrawerLayout"
	pod 'KafkaRefresh'
	pod 'AFNetworking', '~> 3.0'
	pod 'SDWebImage'
	pod 'Socket.IO-Client-Swift', '~> 15.0.0'
	pod 'MBAutoGrowingTextView', '~> 0.1.0'
	pod 'UITextView+Placeholder' 
	pod 'FBSDKLoginKit'
	pod 'GoogleSignIn'
	pod 'Firebase/Core'
	pod 'Firebase/Messaging'
	pod 'IQKeyboardManager'
  # Pods for snackspopnew

end
